### ISSUE TITLE
Keep historic jobs

### ISSUE THREAD

**Issue by jdlrobson** [wikimedia/pixel#108]
https://pixel.wmcloud.org/reports/desktop/index.html currently shows the latest master against the release branch.
It would be useful to generate and preserve reports for each release so that in the event of unbreak now/regressions we can look back at history to identify where the issue was introduced.

e.g. https://pixel.wmcloud.org/reports/desktop/1.39.0-wmf.27 would show us the difference between 1.39.0-wmf.27 and 1.39.0-wmf.26.

THis could be done with a cronjob, but ideally would happen by dynamically setting the directory of the report on each run.

**Comment by nicholasray** [comment]
I agree that this would be useful

**Comment by nicholasray** [comment]
Moving discussion to https://phabricator.wikimedia.org/T317668
