### ISSUE TITLE
On M1 mac (and maybe other machines), tests sporadically hang

### ISSUE THREAD

**Issue by nicholasray** [wikimedia/pixel#113]
Occasionally, the tests on my m1 mac sporadically hang without any timeout or exit. It just stands still e.g.:

```
CREATING NEW REFERENCE FILE
Browser Console Log 0: JSHandle:BackstopTools have been installed.
SCENARIO > Tree (#vector)
Browser Console Log 0: JSHandle:BackstopTools have been installed.
SCENARIO > Tree (#vector)
SCENARIO > Tree (#vector)
x Close Browser
SCENARIO > Tree (#vector)
x Close Browser
x Close Browser
x Close Browser
```

Might be related to the docker image change as I remember encountering this issue in a prior revision of the PR): https://github.com/wikimedia/pixel/commit/6f64b388e9ac280bf4f7149d4e649477d1ed7d61

@moabualruz Do you experience this issue?

**Comment by nicholasray** [comment]
Might be noticing this issue on pixel.wmcloud.org as well . It looks like the `pixel_visual-regression` container just hangs without exiting sometimes

**Comment by nicholasray** [comment]
@jdlrobson have you noticed this issue with the tests running and then hang?

**Comment by jdlrobson** [comment]
I don't think I've seen this issue myself.

**Comment by nicholasray** [comment]
Moving this discussion to https://phabricator.wikimedia.org/T311573
