### ISSUE TITLE
pixel.wmcloud outdated

### ISSUE THREAD

**Issue by jdlrobson** [wikimedia/pixel#91]
cc @jandre3000 (forgot to ping you yesterday before I leave)
Looks like some error in the job is causing all tests to fail. Likely want to fix that or find some way to run manually before next week's train.

**Comment by jdlrobson** [comment]
I looked into this today. Looks like `php maintenance/update.php --quick` is failing. Works fine for me locally.

**Comment by jdlrobson** [comment]
Found this thread https://stackoverflow.com/questions/67500484/how-to-fix-database-connection-error-using-docker-mediawiki-image but not sure if it's relevant as I'm no Docker expert.

**Comment by nicholasray** [comment]
Is this still an issue or can it be closed?
