### ISSUE TITLE
(Sticky TOC) MediaWiki_Test_anon_scroll_vector-2022_scroll_0_viewport_0_phone.png  test is flaking

### ISSUE THREAD

**Issue by jdlrobson** [wikimedia/pixel#95]
It seems like there is a JavaScript delay showing the button, so when scrolling sometimes it doesn't appear

Example failure
<img width="1381" alt="Screen Shot 2022-08-15 at 7 35 16 PM" src="https://user-images.githubusercontent.com/148752/184694932-94fa12fa-1933-40a1-95a8-77a99d80af61.png">

**Comment by nicholasray** [comment]
Moving discussion to https://phabricator.wikimedia.org/T317672
