### ISSUE TITLE
(Vue module) filename: MediaWiki_Test_logged-in_vector-2022_scroll_search-sticky_search-focus_0_viewport_0_desktop-wide.png  is flaking

### ISSUE THREAD

**Issue by jdlrobson** [wikimedia/pixel#99]
<img width="1363" alt="Screen Shot 2022-08-31 at 4 44 55 PM" src="https://user-images.githubusercontent.com/148752/187803866-61182a29-71df-47d1-b535-1c4363076adc.png">

**Comment by jdlrobson** [comment]
Still happening

**Comment by nicholasray** [comment]
Assuming this has been fixed now, if not please let me know!
